### ISSUE TITLE
Add a servo motor as an agitator that swings back and forth when activated

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/SteamBot2017#100]
Look at the code we did for testing.  I can see a timer involved that pushes the servos in one directions and if a timer goes off pushes it in the other direction.

**Comment by ammenzl7** [comment]
In the Servo branch is code to switch the direction of the servo every 0.5 seconds. Commented out is code to look at the position of the servo, and switch directions when it reaches the endpoints. Needs testing, and need to choose which set of code to use.
