### ISSUE TITLE
Try to get Control system Award

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/SteamBot2017#101]
Details here:

Innovation in Control Award Sponsored by Rockwell Automation
Updated

November 1, 2016
Events Where It Is Awarded

District Events
Regional Competitions
District Championships
FIRST Championship Division
Description

Celebrates an innovative control system or application of control components – electrical, mechanical or software – to provide unique machine functions.

Guidelines

A team spokesperson must be able to identify and describe the controls innovation and can trace its conception, design, manufacturing/assembly, or deployment.
The control system is innovative and unique. It is integrated with the machine, human players, strategy, etc. in concept and execution.
The innovation is practical; it addresses the game’s challenge. It is not just a cute idea and is reliable under the stress of competition.

**Comment by abcurrie** [comment]
https://www.firstinspires.org/resource-library/frc/awards-based-on-creativity-innovation

**Comment by JessicaKline** [comment]
Is this something that someone would have to specifically present for, or is it just talking to the judges when they come around the pits?

**Comment by Shalmezad** [comment]
It's mainly talking to judges when they come around to the pits based on my understanding of the award. Would strongly recommend doing some reading on the various Chief Delphi threads on it (such as [this](https://www.chiefdelphi.com/forums/showthread.php?t=76306) )
I'm assuming Mr. Currie has something in mind, so would be curious to see where this ends up. Keep in mind most of the judges aren't programmers, so be sure to make a friendly diagram/flow-chart/write-up if there's something programming related.

**Comment by abcurrie** [comment]
The forum is talking to the judges in the pits when they come around.  However a book or storyboard with talking points would be a great way to capture visually what we have done and to capture the broad range of topics that describe what we did to program and adapt to problems.

 

I already have several pages of notes to start.  What I think we need is some student participation for the various sections to put it all together.

 

Sandy

**Comment by JessicaKline** [comment]
https://docs.google.com/a/midlandps.org/document/d/1UeWtnz8bDOTa2zYZOr-NM1GoSQxbfl8xBeYmRxGcJfw/edit?usp=sharing 

This link should be to a big doc where we can print everything

**Comment by Shalmezad** [comment]
Just a heads up, this repository is public (ie: others can see this issue and click that link), and that document doesn't have any limitations on who can edit it (I could open a window without logging in and delete random things). May want to consider locking down the editing permissions.

**Comment by JessicaKline** [comment]
Now you can only view the final doc. I will play around with the possibilities later. If you write something post it/ a link to it in here. I will copy it in.
