### ISSUE TITLE
Look into "FRCDashboard"

### ISSUE THREAD

**Issue by Shalmezad** [The-Charge/SteamBot2017#102]
Save this for the offseason, or if you [start running out of things to do](http://www.motifake.com/image/demotivational-poster/1201/youre-kidding-right-bobcat-sceptic-humor-demotivational-posters-1325960242.jpg).
Found an amazing looking dashboard [here](https://www.reddit.com/r/FRC/comments/636uoz/team_6325_also_presents_the_sexiest/):
![Amazing dashboard](https://i.redditmedia.com/fuvqoJEaJBFYTtcKL2v8ZRhvX2OFjC2V_qrw-gq8wBo.png?w=1024&s=6ecdc92453a18a0c4dce1277e618761d)

Appears to use python to allow using html/css/javascript to build much more pleasant looking interfaces. Basically the SFX dashboard, but with styling that is well-documented and familiar. 

The code used for that image can be found [here](https://github.com/ResetRobotics/2017-robot-code/tree/master/Dashboard) and the main codebase for the project can be found [here](https://github.com/FRCDashboard/FRCDashboard).

**Comment by abcurrie** [comment]
Cool Beans!  But I take it will need a real programmer to make it work!

 

Sandy
