### ISSUE TITLE
Try to save as much time as possible during the shooting auton

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/SteamBot2017#103]
Apparently we are missing the auto boiler points by only a second or two. Can we make the robot drive faster, or take less time between actions?

**Comment by abcurrie** [comment]
I would be worried about changing anything prior to putting the gear on the
peg backing up.  After that I am comfortable with changes.  Do you know of
things we could change that would save time?

**Comment by ammenzl7** [comment]
Maybe we could run the shooter and collector in parallel while driving to current toward the boiler? This might allow the robot to instantly start shooting once it arrives at the boiler. Could save at least one second.

Another option might be increasing the velocity the robot drives at after delivering the gear (Not changing any code for driving to the peg and delivering the gear).

Any other thoughts?

**Comment by Shalmezad** [comment]
Could try kicking into high gear as you shouldn't need as much accuracy that delivering a gear does.... but would require a bit of tuning to pull off.

**Comment by ammenzl7** [comment]
Actually if I remember correctly, wasn't motion magic originally tuned for high gear? Or am I thinking of something else?

Maybe we could try kicking it into high gear every time we want to drive (Low gear for turning), and give it a go on a practice match...

**Comment by JessicaKline** [comment]
Motion magic is tuned for low gear, but works comparably in high gear. Relative turning is tuned for high gear so we wouldn't have to switch gears. Shooting while driving might waste balls and/or get us penalties. Turning up drive to current might save time though.

**Comment by ammenzl7** [comment]
In regards to shooting while driving, we would wait until the drive to current is finished, and then move on to running the indexer. The auton is set up right now to turn on the shooter, and wait a second so it is all set to shoot the balls. This is one second where we are essentially just sitting there. My idea was to start running the shooter while driving to eliminate that one second.

I like the idea of increasing the drive to current speed, but we might have to increase the max current allowed so as to make sure the robot doesn't stop instantly.
