### ISSUE TITLE
Create repository for "Loons Baseball Bot"

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/SteamBot2017#104]
Leadership wants to treat this robot like a regular build season robot. The robot might also fire T-Shirts.

**Comment by abcurrie** [comment]
Done,  look for BaseBallBot2017

**Comment by Yand1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/OgnHPaBu/1-test)
