### ISSUE TITLE
TurnNDegreesAbsolute with PID Command

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/SteamBot2017#2]
This could help with TurnNDegreesRelative too.

**Comment by ammenzl7** [comment]
Works, tuned PID values. Need to look into I-zones.

**Comment by abcurrie** [comment]
Don't see Izone on software PID controller.  Could do something like this

sign = (output == 0) ? 0 : (output > 0) ? 1 : -1;
min_speed=.1
then

        RobotMap.driveTrainLeftFrontMotor.pidWrite(output + ( sign*min_speed));
        RobotMap.driveTrainRightFrontMotor.pidWrite(-output + ( sign*min_speed));

This would give a minumum speed under any conditions and then allow PID to just nudge it in the right direction.  P would then have to be much smaller and might be able to get rid of I.
