### ISSUE TITLE
Drive until you hit something

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/SteamBot2017#21]
As part of autonomous we need a way to drive forward the last 1-2 feet until we hit the wall.  What I envision is some way to drive slowly until the motors see a large increase in current over some set value.

The question is what control mode would be best.  It might be best to use speed control.  The MSC's would try to maintain speed by increasing voltage and hence the total current would start to climb.

This should not be too hard to test.  We already have a way to do speed control.  We would need to add current monitoring into the is_finished part of the command

**Comment by ammenzl7** [comment]
Should theoretically work, needs testing.
