### ISSUE TITLE
Ultrasonic for wall detection for the peg

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/SteamBot2017#22]
Would ultrasonic be an option to see the wall and detect either when to stop or more likely maybe when to open the doors to allow the peg to engage the gear.  I thought we got some kind of sensor in the KOP's

**Comment by Shalmezad** [comment]
https://firstfrc.blob.core.windows.net/frc2017/Checklists/2017KOPChecklist-GrayTote.pdf
Page 8, looks like we should have a "HRLVMaxSonar-EZ" rangefinder.

Datasheet is here:
http://www.maxbotix.com/documents/HRLV-MaxSonar-EZ_Datasheet.pdf

Minimum distance on it is 30 cm (11.8 inches). 
Out of the different ways to interface with it, analog is probably going to be the easiest.

**Comment by mike-r** [comment]
I have used those before.  They work down to a couple of cm but you need to average several readings.  Their spec of 30cm is to see a small object reliably.   If you are looking for your distance to a wall it will work well much closer. 


Mike

**Comment by Shalmezad** [comment]
@mike-r Thanks for the clarification.
One of the things we may want to look into (if we need it) is the oversampling and averaging capabilities of the roboRIO that's built right in. I noticed this last year when digging through some of the documentation, but didn't really have a use for it at the time:
http://wpilib.screenstepslive.com/s/4485/m/13809/l/599718-analog-inputs

And if that doesn't work, a good ol' java queue should take care of averaging it if we really need it.

**Comment by ammenzl7** [comment]
- [x] Create ultrasonic subsystem.
- [x] Find distance per volt (May need to be experimentally calculated).
- [x] Write voltage and distance in writeDebugValues().
- [x] Add writeDebugValues() to Robot.readAndWriteDashboardValues().

**Comment by wittcd** [comment]
Need to test accuracy of equation.
