### ISSUE TITLE
Set Control Modes

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/SteamBot2017#23]
- [x] Single method in DriveTrain setControlMode().
- [x] Single method it DriveTrain getControlMode().
- [x] Every command explicitly call setControlMode().
- [x] Bonus: getControlMode() in initialize. setControlMode() to what it was in end().

**Comment by sreeramsa** [comment]
Should be done and needs testing. Is currently on Set_Control_Modes branch.
