### ISSUE TITLE
Create two identical Button Boxes for Drive Team

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/SteamBot2017#28]
Design one (With input from the Drive Team).
Create two (With Electrical Team)

**Comment by JessicaKline** [comment]
Btn Box Axis Organization

1   2   3   4
5   6   7   8
9   10 11 12
13 14 15 16

1-8 -> press btns
1 is flaky

9-16 -> switch

Btns Needed

Rope Climb : 2
Rope Climb Override: 3
Turn 180: 4
Drive to Win (Vision to Target): 5

Gear Doors: 9
Plunger: 10
Shooter: 11
Indexer: 12
PickUp: 13

**Comment by JessicaKline** [comment]
Final:

Climb 5
Climb Override 6
Turn 180 7
DriveToWin 8

Doors 9
Plunger 10
Shooter 13
Indexer 14
Pick Up 16

**Comment by JessicaKline** [comment]
turn 180 relegated to Joystick -- needs to be done by someone

**Comment by ammenzl7** [comment]
Need a button to turn on and off camera lights.

**Comment by ammenzl7** [comment]
Turn 180 has been relegated to joystick, button has been added to button box to turn camera lights on and off.
