### ISSUE TITLE
Write out DO's for LED Sign (Also RGB LED Interface)

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/SteamBot2017#4]
Need to write out 4 digital outputs. These will interface with an LED Sign that can display 1 of 16 predetermined strings.
Will need to figure out best way to do this; hard or soft buttons, triggers, commands, etc.

**Comment by ammenzl7** [comment]
Also, program an interface to the RGB Lights using the provided Java Libraries.

**Comment by Menzla** [comment]
I'd suggest making sure the LED subsystem is finished before starting this task.

**Comment by wittcd** [comment]
ready to merge - is same as the critical version
