### ISSUE TITLE
Create forward drive button for Cam

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/SteamBot2017#70]
Using the gyro, when button is held don't turn.

Would like to have this ready for competition.

**Comment by Shalmezad** [comment]
If you can't come up with a different way to do this, might I recommend the following?

- [ ] Add 2 fields to DriveTrain
  - float driveLockAngle
  - bool driveLocked = false
- [ ] 2 commands, tied to your buttons:
  - [ ] DriveTrainStraightLock
    - onButtonPressed
    - Instant command
    - Set driveLockAngle (getYaw())
    - Set driveLocked = true
  - [ ]  DriveTrainStraightUnlock
    - onButtonReleased
    - Instant command
    - Set driveLocked = false
- [ ] In DriveTrain.run()
    - Check if(driveLocked)
    - If true, look at MathUtil.calcDirection(getYaw(), driveLockAngle)
    - Use that to add a correction to leftSpeed/rightSpeed (I believe it returns -1 to turn left, 1 to turn right) before sending to the motors
- [ ] Test, test, test, and test some more.

**Comment by wittcd** [comment]
I used one command which just switches the lock.

**Comment by wittcd** [comment]
Is it okay if I used a when pressed that toggles lock on/off?

**Comment by wittcd** [comment]
Also, which drive modes do I need to implement this on? (Which ones does Cam use?)

**Comment by wittcd** [comment]
Also, I just changed run so that if driveLocked is true, it will average the joystick inputs and then feeds that into both motors. I am not using the gyro.
