### ISSUE TITLE
Ask Drive Team

### ISSUE THREAD

**Issue by JessicaKline** [The-Charge/SteamBot2017#80]
- [ ] Cam: Are you using low gear as you approach peg/ when you want fine control?
- [ ] auto plunge after opening the doors?
- [ ] Should we add a btn to auto deliver/ clean up after we deliver the gear
- [ ] can we get the indexer to run faster please?

**Comment by ammenzl7** [comment]
1.) Cam was not using low gear, will test with it once the robot is working.
2.) Kiley is fine either way, would like to try it out.
3.) Kiley is fine either way, would like to try it out.
4.) This is being worked on.
