### ISSUE TITLE
Create CG to open/close doors AND plunge/retract

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/SteamBot2017#85]
Open doors, wait, plunge.
Retract, wait, close doors.

**Comment by abcurrie** [comment]
This may need to be re-opened.  We seem to have lost the delay time between
the gear door and the plunger that we had.

**Comment by JessicaKline** [comment]
This isn't the one that lost the delay. This one has a .25 sec delay. We thought it might need fine tuning with the timing. It was the autons that the timing has been lost in.
