### ISSUE TITLE
MERGING

### ISSUE THREAD

**Issue by JessicaKline** [The-Charge/SteamBot2017#88]
Have fun Andrew 😄 there are 7 branches for you to merge in on SourceTree. Best of luck.

**Comment by ammenzl7** [comment]
To be merged into Merging:

- [x] Yaw_Reset
- [x] InvertDrive_whenToggled
- [x] OpenCloseCG
- [x] AutonChanges
- [x] DriveForward
- [x] SpeedControlCommand
- [x] ClimberTesting
-------------------------------------------------------------------------------------------------------------------
- [x] Update Master

**Comment by ammenzl7** [comment]
Done, would like to test everything again to make sure nothing went wrong in the merging process.

**Comment by ammenzl7** [comment]
What here needs merging?
